services:
  public-holiday-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      # Override Redis host so that Spring Boot connects to the Redis container
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
